info:
    app:
        description: Master Spring Boot
        name: Spring Boot Master Class Course
        version: 1.0.0
    company:
        name: Amigoscode
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: info,health,health-path, prometheus
    info:
        env:
            enabled: true
server:
    error:
        include-binding-errors: always
        include-message: always
        include-stacktrace: ON_PARAM
spring:
    datasource:
        driver-class-name: org.h2.Driver
        initialization-mode: always
        password: hello
        url: jdbc:h2:mem:testdb-dev-environment
        username: hello
    h2:
        console:
            enabled: true
            path: /h2-dev
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    main:
        banner-mode: 'off'
    output:
        ansi:
            enabled: ALWAYS
    sql:
        init:
            mode: always
            platform: h2
